title: Chris Cochet # your name (or website title) here
logo: "/images/Chris C.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>  
  Experienced analytics professional with a technology and consulting background focused on data science to analyze customer behavior, enhance products and improve decision making.
  <br><br>
  I love outdoors and that's why I live in New Zealand ! 
  <br><br>
  <a href="https://www.linkedin.com/in/christophercochet/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
